### ISSUE TITLE
docs-scraper is not compatible with python 3.11

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/docs-scraper#285] opened 2022-11-30 16:05 UTC
Because of selenium's dependency `exceptiongroup` we are not compatible with python `3.11`. 

```
   "exceptiongroup": {
            "hashes": [
                "sha256:542adf9dea4055530d6e1279602fa5cb11dab2395fa650b8674eaec35fc4a828",
                "sha256:bd14967b79cd9bdb54d97323216f8fdf533e278df937aa2a90089e7d6e06e5ec"
            ],
            "markers": "python_version < '3.11'",
            "version": "==1.0.4"
        },
```

The latest version of `selenium` seems to remove this dependency See #283. Nonetheless, we should still ensure that we are compatible with python 3.11 once the PR is merged.

**Comment by sanders41** [comment] 2023-06-02 12:40
I just testing running with 3.11.3 and got no errors. @BoDonkey do you have a config file I can test with to see if I can reproduce the error?

**Comment by BoDonkey** [comment] 2023-06-02 13:05
@sanders41 Heh - older BoDonkey is hating younger BoDonkey that did this and then left stuff hanging around ... somewhere. I'll dig in and (hopefully) get back to you soon.

**Comment by alallema** [comment] 2023-09-06 11:05
With no news on this issue and no success in reproducing the bug, I'm closing it. Feel free to reopen it if the issue is still running

**Closed by alallema** 2023-09-06 11:05 UTC
Labels: bug, needs more info
