### ISSUE TITLE
UTF-8 page content is not stored properly

### ISSUE THREAD

**Issue by filiplikavcan** [meilisearch/docs-scraper#367] opened 2023-04-15 11:23 UTC
**Description**
Almost all pages on trnavka.sk domain are indexed properly. This one is not: https://trnavka.sk/te-my/ The text is utf-8 but is not stored properly in search index.

**Expected behavior**
Properly encoded utf-8 texts in search index.

**Current behavior**
Not properly encoded utf-8 texts in search index.

**Screenshots or Logs**
<img width="630" alt="Screenshot 2023-04-15 at 13 19 10" src="https://user-images.githubusercontent.com/1244233/232210768-63b76df9-07a2-4df0-936f-233b73490f5f.png">

**Environment:**
- OS: MacOS
- Meilisearch version: 1.1.0
- docs-scraper version: 0.12.8

**Comment by sanders41** [comment] 2023-04-16 12:47
Can you provide your config? For anyone else looking into this the page does report as being correctly utf-8 encoded.

```py
import httpx


def main() -> int:
    response = httpx.get("https://trnavka.sk/te-my/")
    print(response.encoding)
    print(response.charset_encoding)

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
```

```console
utf-8
utf-8
```

**Comment by filiplikavcan** [comment] 2023-04-17 06:58
My config:

```json
{
  "index_uid": "docs",
  "start_urls": ["https://trnavka.sk/"],
  "stop_urls": [],
  "selectors": {
    "lvl0": {
      "selector": ".not-existing-selector",
      "global": true,
      "default_value": "Článok"
    },
    "lvl1": {
      "selector": "head title",
      "global": true,
      "default_value": ""
    },
    "text": ".content"
  }
}
```

**Comment by sanders41** [comment] 2023-04-19 11:40
I'm using python 3.11.3 on Linux, but neither of those should make a difference from what you have. Are you using the docker docs-scraper image? I ran it without docker, maybe that is the difference?

**Comment by filiplikavcan** [comment] 2023-04-19 13:25
I ran it without docker too.

**Comment by sanders41** [comment] 2023-04-19 15:46
My default system language is US English, is your's Slovak? Really this one is a wild guess and I don't have a good idea for a solution if that is the issue, I'm just looking for anything different in our setup at this point to give a starting point for trouble shooting.

**Comment by filiplikavcan** [comment] 2023-04-19 16:49
I think it is english. How can I find out? LC_ALL and LANG are not defined/empty.

FYI: I printed `zlib.decompress(response._body, 15+32).decode('utf-8')` in scraper/src/custom_downloader_middleware.py in process_response method and it prints correctly decoded utf-8 string:

```html
<title>Té – my &#8211; Saleziánske dielo na Trnávke</title>
```

**Comment by sanders41** [comment] 2023-04-19 18:55
It sounds like you language setting is the same as mine also. If you search for the record outside of the we front in (with curl for example) do it look correct? 

https://www.meilisearch.com/docs/reference/api/search#example

**Comment by filiplikavcan** [comment] 2023-04-19 19:02
Nope:

```json
{
    "hits": [
        {
            "hierarchy_radio_lvl0": null,
            "hierarchy_radio_lvl1": null,
            "hierarchy_lvl0": "Článok",
            "hierarchy_lvl1": "TÃ© â my – SaleziÃ¡nske dielo na TrnÃ¡vke",
```

**Comment by sanders41** [comment] 2023-04-19 19:08
If you take the json for that page and send it yourself without using the docs-scraper does it work that way. Maybe we can confirm or rule out the docs-scraper being the issue doing this.

https://www.meilisearch.com/docs/reference/api/documents#add-or-replace-documents

**Comment by filiplikavcan** [comment] 2023-04-19 19:40
Hm, I just found out that it works when I remove 😮 emoji from the page.

**Comment by sanders41** [comment] 2023-04-19 19:55
> Hm, I just found out that it works when I remove open_mouth emoji from the page.

That is interesting I'm trying to see if I see anywhere that could cause the problem. As a quick check can you run this in a python REPL just to verify it works as expected for you (I expect it will):

At the command line type `python`

```py
import json
t = '{"test": "😮"}'
print(json.loads(t))
```

You should see `{'test': '😮'}`. Then type `quit()` to exit the REPL

**Comment by sanders41** [comment] 2023-04-19 20:14
One more thing you can try, but I don't think will make a difference, is cloning the repo and running from the `main` branch. That is where I am running from. I am only seeing so updates to dev only dependencies since the last release so I don't expect it to make a difference.

@alallema I think I saw you all are at a company meeting this week? When you get back I would be curious to see if one of you can reproduce the issue.

**Comment by filiplikavcan** [comment] 2023-04-20 09:20
Yup, I see `{'test': '😮'}` and I am on main branch. Last commit:

```
commit 7942cdd394743cab3c1536f9260d2ceaed81d018 (HEAD -> main, tag: v0.12.8, origin/staging, origin/main, origin/HEAD)
Merge: 2b49032 f14ae6d
Author: meili-bors[bot] <89034592+meili-bors[bot]@users.noreply.github.com>
Date:   Tue Mar 14 12:44:51 2023 +0000
```

**Comment by alallema** [comment] 2023-04-24 08:22
Hi @filiplikavcan,
Thanks for raising this issue. And thank @sanders41 to take care of it. I will check this on my side.

> @alallema, I think I saw you all are at a company meeting this week. When you get back, I would be curious to see if one of you can reproduce the issue.
Yes, you are right! I will try and I came back as soon as possible.

**Comment by alallema** [comment] 2023-05-22 10:04
Hi @filiplikavcan and @sanders41,
> When you get back I would be curious to see if one of you can reproduce the issue.

I have tried to reproduce the issue but I have no problem retrieving the documents either:
```
{
	"hits": [
	{
		"hierarchy_radio_lvl0": null,
		"hierarchy_radio_lvl1": null,
		"hierarchy_lvl0": "Článok",
		"hierarchy_lvl1": "Té – my – Saleziánske dielo na Trnávke",
		"hierarchy_lvl2": null,
		"hierarchy_lvl3": null,
		"hierarchy_lvl4": null,
		"hierarchy_lvl5": null,
		"hierarchy_lvl6": null,
		"content": "Diskusie na aktuálne témy Té – my 
		...
		dobrovoľník \nAnička Lacková, študentka KAN",
		"objectID": "5f7d339b9f98662b44c3655b02f9acc6d4a5a71e",
		"anchor": null,
		"url": "https://trnavka.sk/te-my/"
	},
	"query": "Diskusie",
	"processingTimeMs": 7,
	"limit": 20,
	"offset": 0,
	"estimatedTotalHits": 14
}
```
It's annoying not to find out where this one comes from but if you can get the scraper to work on your side @filiplikavcan and we aren't able to reproduce the problem I will close this issue.

**Comment by alallema** [comment] 2023-08-03 08:22
With no hear about this issue and can't reproduce it, I'll close it.

**Closed by alallema** 2023-08-03 08:22 UTC
Labels: needs more info
